// ========== 完整剧本数据 ==========
// type: bg | narrate | dialogue | choice | affinity | jump | route | end | label
const SCRIPT_DATA = [
{label:'start'},{type:'bg',id:'black'},
{type:'narrate',text:'这是一个关于「败北」的故事。准确地说，是关于那些在恋爱中败下阵来的女孩子们的故事。'},
{type:'narrate',text:'而我——温水和彦，原本只是一个坐在教室角落，没有任何朋友的「背景路人」。'},
{type:'narrate',text:'直到那一天，在那间家庭餐厅里，我遇见了她——'},
{jump:'ch1'},

// ===== 第一章：家庭餐厅的邂逅 =====
{label:'ch1'},{type:'bg',id:'restaurant'},
{type:'narrate',text:'那个周末的傍晚，我像往常一样一个人坐在家庭餐厅的角落，一边喝着饮料一边看轻小说。'},
{type:'narrate',text:'隔壁座位上，一对高中生男女正在谈话。男孩是青梅竹马，女孩是被甩的那一方。'},
{type:'narrate',text:'我偷偷瞄了一眼。那个女孩有着一头栗色长发，长相端正。她一边哭一边吃着咖喱饭，眼泪掉进盘子里。'},
{type:'narrate',text:'然后——我的目光和那个女孩对上了。她用红肿的眼睛狠狠瞪了我一下。'},
{type:'narrate',text:'那个男孩很快就离开了。女孩独自留在座位上，开始翻找钱包——一分钱都没有。'},
{type:'narrate',text:'说实话，这时候我应该继续低头看书，假装什么都没看到。但不知为何，我站了起来。我走到她的座位前，递过去一千日元。'},
{type:'dialogue',char:'WZ',text:'「给你。」'},
{type:'dialogue',char:'YN',text:'「……哈？你、你谁啊？变态？跟踪狂？还是想用一千日元泡我？」'},
{type:'dialogue',char:'WZ',text:'「都不是。我只是刚好坐隔壁，刚好看到了。就当是借给你的好了，下次还。」'},
{type:'narrate',text:'她盯着我看了好一会儿。然后突然抢走那张一千日元，把脸埋进手臂里。'},
{type:'dialogue',char:'YN',text:'「……谢谢。」她的声音闷闷的，带着浓重的鼻音。'},
{type:'narrate',text:'这是我第一次和一个失恋的女孩说话。后来我才知道，她的名字叫八奈见杏菜。'},
{type:'affinity',char:'yn',val:1},
{type:'bg',id:'classroom'},
{type:'narrate',text:'几天后，在学校走廊上。'},
{type:'dialogue',char:'YN',text:'「喂！一千日元同学！」八奈见在校门口堵住了我。'},
{type:'dialogue',char:'YN',text:'「不还怎么行？不然你这种闷骚男会脑补『她是不是想借还钱的借口再见我一面』的吧？」'},
{type:'dialogue',char:'WZ',text:'「……我才不会。话说回来，我叫温水和彦。」'},
{type:'dialogue',char:'YN',text:'「温水？好奇怪的名字。行吧温水君，欠你的人情我会记住的。」'},
{type:'narrate',text:'她就这么转身走了。我以为这就是我们之间的最后一面。——但我错了。'},
{type:'bg',id:'hallway'},
{type:'narrate',text:'几天后，我在走廊上被一个矮小的女生拦住了。她低着头，双手紧紧握着一部手机。然后，她把手机屏幕举到我面前。'},
{type:'narrate',text:'屏幕上的文字写着：「请加入文艺社。你是唯一的希望。」'},
{type:'dialogue',char:'WZ',text:'「……什么？」'},
{type:'narrate',text:'这个小小的女生——小鞠知花——是文艺社的社员。文艺社已经快要废社了。'},
{type:'narrate',text:'理由：我看起来像「轻小说里的男主角」。……这算什么理由？但最终我还是加入了。'},
{type:'affinity',char:'xj',val:1},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'文艺社的社办是一间位于旧校舍的小教室。推开门的瞬间，我闻到了旧书的味道。'},
{type:'narrate',text:'社长玉木慎太郎戴着眼镜，副社长月之木古都笑容灿烂。还有一个人——一个留着长发的女生倒在窗边的沙发上，像丧尸一样。'},
{type:'dialogue',char:'WZ',text:'「……真的是活的吗？」'},
{type:'dialogue',char:'ZMX',text:'「活的哦……」她动了！虽说只是动了动手指而已。'},
{type:'affinity',char:'zmx',val:1},
{type:'narrate',text:'就这样，我的文艺社生活开始了。当时的我还不知道，这间小小的社团——将成为一群「败北女角」的避风港。'},
{jump:'ch2'},

// ===== 第二章：奔跑的理由 =====
{label:'ch2'},{type:'bg',id:'track'},
{type:'narrate',text:'石蕗高中有一条标准四百米的田径跑道。每天放学后，都能看到田径队的队员在上面奔跑。'},
{type:'narrate',text:'而在所有人的前面，总有一个小麦色肌肤的女生在领跑。她叫烧盐柠檬。'},
{type:'narrate',text:'我第一次认真注意到她，是在某个炎热的下午。'},
{type:'narrate',text:'她正从体育仓库里搬运器材，一个人。'},
{type:'dialogue',char:'WZ',text:'「需要帮忙吗？」'},
{type:'dialogue',char:'SY',text:'「哎？不用不用，我是田径队的，这点东西完全没问题——」'},
{type:'narrate',text:'她一边笑着一边说没问题，然后下一秒就栽倒了。'},
{type:'bg',id:'infirmary'},
{type:'narrate',text:'我把她搬到了保健室。烧盐柠檬躺在病床上，额头上贴着退烧贴。'},
{type:'dialogue',char:'XB',text:'「哦呀，有便当？让她吃点吧，补充盐分。」小拔老师坏笑着看了我一眼。'},
{type:'dialogue',char:'SY',text:'「……阿温的便当？那就不客气了。」她用我的筷子吃我的午饭。'},
{type:'narrate',text:'小拔老师在旁边发出了诡异的笑声：『间接接吻～』'},
{type:'affinity',char:'sy',val:1},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'几天后。文艺社里，小鞠抱着一堆文件跑了进来。她看起来很惊慌——'},
{type:'dialogue',char:'XJ',text:'「……本子！她们把我的本子没收了！……BL的。」'},
{type:'dialogue',char:'YZM',text:'「什么？小鞠的本子被没收了？那些可都是我的宝物啊！！」月之木副社长拍案而起。'},
{type:'narrate',text:'这就是我和学生会的第一次接触。而那个没收本子的凶手——正是副会长马剃天爱星。'},
{jump:'ch3'},

// ===== 第三章：合宿与初恋的终结 =====
{label:'ch3'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'暑假。文艺社决定在学校的旧校舍办一次合宿。名义上是「为学园祭做准备」。'},
{type:'bg',id:'shrine'},
{type:'narrate',text:'深夜的神社。我睡不着出来散步，却在石阶上看到了烧盐柠檬。她一个人坐在石阶上，月光把她的剪影拉得很长。'},
{type:'dialogue',char:'WZ',text:'「烧盐？」'},
{type:'dialogue',char:'SY',text:'「……阿温。我真的好过分。我今天对他说了很过分的话。」'},
{type:'dialogue',char:'SY',text:'「……绫野君。他有女朋友了。我明明知道的。但是我没办法——没办法控制自己的心情。」'},
{type:'narrate',text:'她终于哭了出来。不是那种无声的眼泪，而是像要把一切激烈的情感都吐出一般的大哭。'},
{type:'narrate',text:'我坐在她身边——隔着一阶石阶的距离。'},
{type:'dialogue',char:'WZ',text:'「你不是坏人。坏人是不会哭的。」'},
{type:'dialogue',char:'SY',text:'「你说这种话，真的很容易让女孩子误会。」'},
{type:'choice',options:[
  {text:'「误会什么？」',affinity:{char:'sy',val:2},next:'ch3_sy1'},
  {text:'「我只是说实话而已。」',affinity:{char:'sy',val:1},next:'ch3_sy2'}
]},
{label:'ch3_sy1'},{type:'dialogue',char:'WZ',text:'「误会什么？」'},
{type:'dialogue',char:'SY',text:'「……误会你是个好人。」她轻轻笑了一下。那笑容在月光下看起来虚弱但真实。'},{jump:'ch3_cont'},
{label:'ch3_sy2'},{type:'dialogue',char:'WZ',text:'「我只是说实话而已。」'},
{type:'dialogue',char:'SY',text:'「……嗯。谢谢你，阿温。」'},{jump:'ch3_cont'},
{label:'ch3_cont'},{type:'affinity',char:'sy',val:1},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'第二天。一切似乎很平静——直到小鞠在走廊上跑过来，眼睛通红。'},
{type:'narrate',text:'她把手机举到我面前，手指在发抖。屏幕上只有三个字：「被拒绝了」'},
{type:'narrate',text:'我听到了从社办传来的声音——玉木社长和月之木副社长宣布他们在交往。小鞠一直暗恋玉木社长。而现在，她的单恋真正结束了。'},
{type:'narrate',text:'文艺社就这样多了两个「败北女角」。一个在深夜神社哭泣，一个在走廊角落里颤抖。'},
{type:'choice',options:[
  {text:'去安慰烧盐',affinity:{char:'sy',val:2},next:'ch3_comfort_sy'},
  {text:'去陪小鞠',affinity:{char:'xj',val:2},next:'ch3_comfort_xj'}
]},
{label:'ch3_comfort_sy'},{type:'bg',id:'track'},
{type:'narrate',text:'我在操场上找到了烧盐。她正在跑步，比平时跑得更用力、更快。我在终点等她。'},
{type:'dialogue',char:'SY',text:'「阿温……你在等我？」'},
{type:'dialogue',char:'WZ',text:'「嗯。」'},{jump:'ch4'},
{label:'ch3_comfort_xj'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'我在社办的角落里找到了小鞠。她正把脸埋在书本后面。我什么都没说，只是坐在她旁边。'},
{type:'narrate',text:'三分钟后，她的手机屏幕推到了我面前。'},
{type:'narrate',text:'「谢谢」——只有一个词。但我知道她说的是什么意思。'},{jump:'ch4'},

// ===== 第四章：学园祭与逃生梯 =====
{label:'ch4'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'暑假结束，第二学期到来。距离学园祭只剩不到一个月。小鞠作为责任编辑，几乎把所有课余时间都投入了进去。'},
{type:'bg',id:'classroom'},
{type:'narrate',text:'某天放学后，我推开社办的门，看到小鞠倒在桌上的稿件里。她瘦小的身体几乎被纸张淹没。'},
{type:'dialogue',char:'WZ',text:'「小鞠，你还好吗？」'},
{type:'narrate',text:'她艰难地爬起来。手机屏幕上的字歪歪扭扭。然后再次倒了下去。'},
{type:'bg',id:'infirmary'},
{type:'narrate',text:'保健室里，小鞠躺在病床上。小拔老师又在旁边坏笑。'},
{type:'dialogue',char:'XB',text:'「温水君啊，你是不是在我这儿办了VIP卡？」'},
{type:'narrate',text:'小鞠费力地举起手机：「不会被废社的。我会努力的。」'},
{type:'dialogue',char:'WZ',text:'「你现在需要休息。别的我来想办法。」'},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'社长会。各个社团的负责人在会议室里汇报学园祭的准备进度。我是代替玉木社长出席的。'},
{type:'dialogue',char:'MAX',text:'「据说你们的编辑在保健室？」天爱星推了推眼镜，锐利的目光直直看过来。'},
{type:'dialogue',char:'WZ',text:'「是的。但她一直在努力。每晚都在熬夜。文艺社不会给学园祭拖后腿。这是她——是副社长想对大家说的话。」'},
{type:'narrate',text:'会议室安静了下来。放虎原会长轻轻鼓掌。'},
{type:'narrate',text:'会议结束后，我走到走廊尽头的逃生梯。意外的是——小鞠站在那里。她没在保健室好好待着。'},
{type:'dialogue',char:'WZ',text:'「你不是应该躺着吗？对不起，擅自冒充了副社长。」'},
{type:'narrate',text:'她摇了摇头。然后用力地打字——'},
{type:'dialogue',char:'XJ',text:'「我不是为了社刊才熬夜的。我是因为——喜欢文艺社。」'},
{type:'narrate',text:'「我说过『我就只有文艺社而已』。但我说错了。我不是只有文艺社。我还有——还有愿意帮我的笨蛋。」'},
{type:'narrate',text:'逃生梯外，夕阳把天空烧成了一片金色。她终于哭了。但没有发出声音。'},
{type:'dialogue',char:'WZ',text:'「我是文艺社的人。所以我会一直在。」'},
{type:'affinity',char:'xj',val:3},
{type:'narrate',text:'她举起手机，屏幕上打好了她想说的话——后来这句话成为了我们之间的暗号：'},
{type:'narrate',text:'「我们文艺社的，都不认输。」'},
{jump:'ch5'},

// ===== 第五章：学生会选举与BL同人志 =====
{label:'ch5'},{type:'bg',id:'hallway'},
{type:'narrate',text:'学园祭结束后不久，学生会选举的公告贴满了走廊。这次选举格外引人注目——因为有两个热门人选：副会长马剃天爱星，以及同班同学樱井弘人。'},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'事情要从文艺社的「BL同人志事件」说起。月之木副社长把最新一期的社刊送到了学生会审核——然后被天爱星以「内容不当」为由没收了。'},
{type:'dialogue',char:'YZM',text:'「不可原谅！！那是艺术！！是文学！！是感动！！」月之木拍着桌子。'},
{type:'narrate',text:'事情闹得越来越大。然后，事情在一个下午出现了转机。'},
{type:'narrate',text:'我在走廊上看到天爱星一个人站在窗边，手里拿着那本被没收的同人志。她的脸红了。红得很厉害。'},
{type:'dialogue',char:'WZ',text:'「……你在看吗？」'},
{type:'dialogue',char:'MAX',text:'「才、才没有！！这只是调查！内容审核！！」她用力合上本子，但手指还在发抖。'},
{type:'narrate',text:'后来我才知道——马剃天爱星，这个看起来无懈可击的认真少女——其实是一个隐藏的BL和二次元爱好者。'},
{type:'affinity',char:'max',val:1},
{type:'bg',id:'cafe'},
{type:'narrate',text:'几天后，天爱星约我去咖啡馆。说是「有重要的事要谈」。'},
{type:'dialogue',char:'MAX',text:'「温水同学——我决定参加学生会选举。我希望你——当我的推荐人。」'},
{type:'narrate',text:'推荐人。这是学生会选举中最重要的角色之一。需要在全校师生面前为自己支持的候选人站台背书。'},
{type:'dialogue',char:'WZ',text:'「为什么是我？你不是讨厌文艺社吗？」'},
{type:'dialogue',char:'MAX',text:'「不……其实我觉得你们很厉害。你们敢写敢画，不在乎别人怎么看。而我——一直不敢让别人知道真正的自己。」'},
{type:'choice',options:[
  {text:'「好。我当你的推荐人。」',affinity:{char:'max',val:3},next:'ch5_yes'},
  {text:'「让我考虑一下。」',affinity:{char:'max',val:1},next:'ch5_think'}
]},
{label:'ch5_yes'},{type:'dialogue',char:'WZ',text:'「好。我当你的推荐人。我相信你能当好会长。」'},
{type:'dialogue',char:'MAX',text:'「……真的吗？谢谢。温水同学，你果然是个……很好的人。」'},{jump:'ch6'},
{label:'ch5_think'},{type:'dialogue',char:'WZ',text:'「让我考虑一下。」'},
{type:'dialogue',char:'MAX',text:'「好。我会等你。」'},{jump:'ch6'},

// ===== 第六章：情人节与妹妹 =====
{label:'ch6'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'二月十四日。情人节。石蕗高中里弥漫着某种说不清的紧张气氛。'},
{type:'narrate',text:'八奈见杏菜一早就来到了社办，手上提着一个纸袋。但她把纸袋随手放在桌上后，就开始若无其事地吃薯片。'},
{type:'dialogue',char:'WZ',text:'「这是什么？」'},
{type:'dialogue',char:'YN',text:'「什么是什么？只是吃的。你！想！多！了！」她把纸袋抱进怀里，脸色微红。'},
{type:'narrate',text:'然后小鞠走了进来。小鞠也拿着一个东西——一个小小的、包装好的盒子。'},
{type:'narrate',text:'她飞快地把盒子放在我面前的桌上，然后用手机打出一行字：「这不是巧克力。只是材料不够，所以做成了心形。」'},
{type:'dialogue',char:'YN',text:'「小鞠你刚才是不是说了心形？」'},
{type:'dialogue',char:'XJ',text:'「没有！！是你说漏嘴了！」'},
{type:'narrate',text:'社办变成了混沌的战场。'},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'放学后，我回到家。妹妹佳树正在厨房里忙活。她今年国中三年级，成绩优秀，家务万能——但只有我知道她的「另一面」。'},
{type:'dialogue',char:'JS',text:'「兄长大人！欢迎回家！今天是情人节，所以佳树特制了巧克力——请在这里签收！」'},
{type:'dialogue',char:'WZ',text:'「……谢谢。」'},
{type:'narrate',text:'她的笑容无懈可击。但眼神里有什么东西正在燃烧。'},
{type:'narrate',text:'晚上，我看到佳树在房间里对着手机轻声叹气。那神情——不像平常那个完美的妹妹。'},
{type:'affinity',char:'js',val:1},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'第二天。我把这件事对八奈见提了一下。'},
{type:'dialogue',char:'YN',text:'「你的妹妹？肯定没有男友啦——有的话你这种人会不知道吗？你觉得你妹妹关心的到底是哪个男生？」'},
{type:'narrate',text:'她的话让我愣住了。佳树平常根本不和其他男生来往。她的世界里——只有我。'},
{type:'dialogue',char:'WZ',text:'「该不会——」'},
{type:'dialogue',char:'YN',text:'「对。温水君你迟钝到这个程度，真的很女性公敌。」'},
{type:'choice',options:[
  {text:'追问佳树的事',affinity:{char:'js',val:2},next:'ch6_ask'},
  {text:'先不去深究',affinity:{char:'yn',val:1},next:'ch7'}
]},
{label:'ch6_ask'},
{type:'narrate',text:'后来我找到佳树，和她坦诚地聊了一次。她笑着说「只是做了一个不好的梦」。但我注意到她的嘴唇在轻轻颤抖。'},
{jump:'ch7'},

// ===== 第七章：婚礼作战与新社员 =====
{label:'ch7'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'新学期。文艺社来了一位新社员。她的名字叫白玉璃子，一年级的学妹。'},
{type:'narrate',text:'第一次见面，她就用那种能融化冰淇淋的笑容看着我，然后——'},
{type:'dialogue',char:'BY',text:'「社长身上，有和姐夫一样的味道呢。」'},
{type:'dialogue',char:'WZ',text:'「……什么味道？」'},
{type:'dialogue',char:'BY',text:'「好人的味道。特别好骗的那种。」'},
{type:'narrate',text:'白玉加入文艺社后，社办的气氛发生了微妙的变化。八奈见说她「太会了」。小鞠说她「有点可怕」。'},
{type:'affinity',char:'by',val:1},
{type:'narrate',text:'不久后，我们得知了一个惊人的消息：白玉因为「非法入侵婚礼会场」被学校处以停学处分。'},
{type:'narrate',text:'在文艺社的集体追问下，她终于说出了原因。'},
{type:'dialogue',char:'BY',text:'「我喜欢邻家的田中老师。从小就喜欢。但他要和我姐姐结婚了。」'},
{type:'dialogue',char:'BY',text:'「我只是想在婚礼上说一句话。就一句。说完了我就不会再喜欢他了。可他们连这最后的话都不让我说。」'},
{type:'narrate',text:'社办里安静了很久。然后，八奈见第一个开口了。'},
{type:'dialogue',char:'YN',text:'「我们帮你。我们文艺社的，都是败犬。被甩过的人最多。」'},
{type:'dialogue',char:'SY',text:'「我也去。说一句再见有什么大不了的。」'},
{type:'narrate',text:'这就是「婚礼作战」的起点。'},
{type:'bg',id:'wedding'},
{type:'narrate',text:'婚礼当天。我们潜入会场，白玉穿上了从更衣室「借」来的婚纱。她站在镜子前的时候，所有人都说不出话了——太美了。'},
{type:'dialogue',char:'BY',text:'「社长，我们来接吻吧。」'},
{type:'dialogue',char:'WZ',text:'「……什么？」'},
{type:'dialogue',char:'BY',text:'「开玩笑的。只是试探一下你的反应。」她笑得很调皮。但里面有多少是真心的，我不知道。'},
{type:'narrate',text:'最终，白玉在婚礼上说了那句「恭喜你们，要幸福哦」。她没有搞破坏。只是笑着，把那句藏了很多年的话说了出来。'},
{type:'narrate',text:'然后她回到更衣室，关上门，哭了整整十分钟。我们在门外等她。每个人都没有走。'},
{type:'choice',options:[
  {text:'敲门问她还好吗',affinity:{char:'by',val:3},next:'ch7_knock'},
  {text:'在外面安静等她',affinity:{char:'by',val:1},next:'ch7_wait'}
]},
{label:'ch7_knock'},{type:'dialogue',char:'WZ',text:'「白玉同学，你还好吗？」'},
{type:'dialogue',char:'BY',text:'「……原来社长是会敲门的啊。不太好。但是比刚才好多了。」'},{jump:'ch7_end'},
{label:'ch7_wait'},
{type:'narrate',text:'有些眼泪是不需要安慰的。让它流完就好。'},{jump:'ch7_end'},
{label:'ch7_end'},{type:'affinity',char:'by',val:1},
{type:'narrate',text:'婚礼作战成功。白玉正式成为了文艺社的一员。她的笑容比以前真诚了一些。'},
{jump:'ch8'},

// ===== 第八章：选举、告白与分水岭 =====
{label:'ch8'},{type:'bg',id:'hallway'},
{type:'narrate',text:'学生会选举进入了最终阶段。我作为天爱星的推荐人，每天放学后都和她一起准备演讲稿、走访社团。'},
{type:'dialogue',char:'MAX',text:'「温水同学——请你只支持我。」某天下午，她在走廊上这样对我说。语气不像平时的她——没有那种硬邦邦的命令感，而是像个在请求的人。'},
{type:'dialogue',char:'WZ',text:'「我一直都只支持你。」'},
{type:'affinity',char:'max',val:1},
{type:'bg',id:'gym'},
{type:'narrate',text:'选举演讲当天。体育馆里坐满了全校学生。天爱星站到了讲台上。她的手在抖，但她深吸了一口气。'},
{type:'dialogue',char:'MAX',text:'「我是一个很固执的人。我不擅长交朋友。我不会说好听话。但是我喜欢这所学校——喜欢在这里努力的每一个人。」'},
{type:'narrate',text:'她说到这里时，鼻血突然流了下来。天爱星用手背擦了擦鼻血，继续说——'},
{type:'dialogue',char:'MAX',text:'「请让我推大家！！」'},
{type:'narrate',text:'掌声如雷。天爱星——高票当选。'},
{type:'bg',id:'bridge'},
{type:'narrate',text:'选举结束的那天傍晚。天爱星约我去向山大池。这座桥上只有我们两个人。'},
{type:'dialogue',char:'MAX',text:'「温水同学。我喜欢你。」'},
{type:'narrate',text:'她站在那里，双手紧紧握着书包的肩带。夕阳把她的侧脸染成了橙色。'},
{type:'dialogue',char:'MAX',text:'「从你答应当我的推荐人那天开始。从你在咖啡馆说『我相信你能当好会长』的那天开始。」'},
{type:'dialogue',char:'MAX',text:'「所以——温水同学，我喜欢你。这、这、这是正式的告白——！！要不要先从朋友开始呢？」'},
{type:'narrate',text:'* 共通线 · 最大分歧点 *'},
{type:'choice',options:[
  {text:'「给我一点时间。」',affinity:{char:'max',val:2},next:'ch8_pending'},
  {text:'认真回答她的感情',affinity:{char:'max',val:5},next:'ch8_max'},
  {text:'委婉拒绝「抱歉，我现在有在想的人。」',next:'ch8_refuse'}
]},
{label:'ch8_pending'},{type:'dialogue',char:'WZ',text:'「给我一点时间。我只是需要想想。」'},
{type:'dialogue',char:'MAX',text:'「好。我会等的。」'},{jump:'route_select'},
{label:'ch8_max'},{type:'dialogue',char:'WZ',text:'「天爱星同学，你的告白——我听到了。」'},
{type:'narrate',text:'她在我面前，认真地说出了她最大的心意。那么，我也应该认真回答她。'},{jump:'route_tengoku'},
{label:'ch8_refuse'},{type:'dialogue',char:'WZ',text:'「抱歉。我现在有在想的人。」'},
{type:'dialogue',char:'MAX',text:'「……那就好。至少你不是在敷衍我。」'},{jump:'route_select'},

{label:'route_select'},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'选举结束后，文艺社恢复了平静的日常。八奈见照常来社办蹭零食。烧盐每天放学后去训练。小鞠在整理稿件。白玉在看窗外。'},
{type:'narrate',text:'而我坐在这群女孩子们的中央，忽然意识到——这间小小的社办，已经不只是一个避风港。它是我不知不觉间，最想回来的地方。'},
{type:'route'},

// ===== 八奈见杏菜线 =====
{label:'route_yanaami'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'—— 八奈见杏菜线：「食欲与恋心，只差一步」——'},
{type:'narrate',text:'天爱星的告白之后，我的生活表面上看没什么变化。但八奈见杏菜变了。她来社办的次数变少了。'},
{type:'bg',id:'hallway'},
{type:'dialogue',char:'YN',text:'「温水君，你最近和天爱星同学走得很近呢。」她手里捏着的薯片袋已经被揉得不成样子。'},
{type:'dialogue',char:'WZ',text:'「因为选举的事。你这几天为什么不来社办？」'},
{type:'dialogue',char:'YN',text:'「因为我最近在减肥。」'},
{type:'dialogue',char:'WZ',text:'「……你？」'},
{type:'dialogue',char:'YN',text:'「什么意思！温水君你这种冷淡态度真的很——很——女性公敌！！」她终于转过头来了。脸是红的。'},
{type:'choice',options:[
  {text:'「你不需要减肥。我觉得你现在这样就很好。」',affinity:{char:'yn',val:3},next:'yn_true'},
  {text:'「是想给谁看吗？」',affinity:{char:'yn',val:1},next:'yn_good'},
  {text:'沉默',next:'yn_normal'}
]},
// 八奈见·真结局
{label:'yn_true'},{type:'dialogue',char:'WZ',text:'「你不需要减肥。我觉得你现在这样就很好。」'},
{type:'narrate',text:'她张了张嘴，什么都没说出来。脸更红了。'},
{type:'bg',id:'rooftop'},
{type:'narrate',text:'第二天中午。我在逃生梯上吃便当。她爬了上来，在我旁边坐下。'},
{type:'bg',id:'station'},
{type:'narrate',text:'白色情人节的前一天。我在车站前遇到了八奈见。她穿着私服——一条简单的白色连衣裙。'},
{type:'dialogue',char:'YN',text:'「温水君！那个——我有话要说。我不想被甩第三次了。」'},
{type:'dialogue',char:'WZ',text:'「你不会被甩的。我也不想被你甩掉。」'},
{type:'narrate',text:'她终于哭了。在车站的灯饰下，她抓着我的袖口不放。然后我伸出手——牵住了她的手。'},
{type:'dialogue',char:'YN',text:'「我不会放手的。以后也是。」'},
{type:'narrate',text:'那天晚上，丰桥车站前的灯饰在头顶闪烁。我们从「被甩的同伴」变成了「不想被抢走的人」。食欲与恋心。原来只差一句话的距离。'},
{type:'end',title:'真结局：灯饰下的牵手',subtitle:'八奈见杏菜线 · 好结局'},
// 八奈见·好结局
{label:'yn_good'},{type:'dialogue',char:'WZ',text:'「是想给谁看吗？」'},
{type:'dialogue',char:'YN',text:'「……你猜。」她没有否认。'},
{type:'bg',id:'cafe'},
{type:'narrate',text:'几天后。她约我去甜品自助店。嘴角沾着奶油，眼眶泛红，但眼神很凶。'},
{type:'dialogue',char:'YN',text:'「另一半——是为了让某个迟钝的笨蛋发现，放着我这么好的女人不要，是他人生的最大损失。」'},
{type:'dialogue',char:'WZ',text:'「我发现了。」'},
{type:'dialogue',char:'YN',text:'「太慢了！！再给你一次机会。对我说一句话。」'},
{type:'dialogue',char:'WZ',text:'「我们不是损友了。最好的朋友，然后是——」我脸红了。她也是。'},
{type:'narrate',text:'甜品店的窗外，丰桥的街景一如既往地安静。一个女生终于不用再假装不在乎。'},
{type:'end',title:'好结局：甜品店的告白',subtitle:'八奈见杏菜线 · 好结局'},
// 八奈见·普通结局
{label:'yn_normal'},
{type:'narrate',text:'我什么都没有回答。她等了一会儿。然后收回了手。'},
{type:'dialogue',char:'YN',text:'「……也是呢。温水君就是这么闷的人。没关系。我真的——真的习惯了被甩。」'},
{type:'narrate',text:'她转身往站台走去。白色的裙摆被风吹起。电车来了。她没有回头。'},
{type:'narrate',text:'我们依然在逃生梯吃便当。她偶尔会抱怨「早知道当年不借那一千日元了」。但每次说完，她都会笑着递过来一盒便当。维持损友。也许有些感情，就是永远留在日落的逃生梯上比较好吧。'},
{type:'end',title:'普通结局：最好的饭友',subtitle:'八奈见杏菜线 · 普通结局'},

// ===== 烧盐柠檬线 =====
{label:'route_yakishio'},{type:'bg',id:'track'},
{type:'narrate',text:'—— 烧盐柠檬线：「奔跑的理由，不只一个」——'},
{type:'narrate',text:'烧盐柠檬每天放学后都在跑步。但最近，她多了一个新理由——她会在每圈经过文艺社社办楼下时看过来。'},
{type:'bg',id:'clubroom'},
{type:'dialogue',char:'SY',text:'「阿温！来比一场百米赛跑吧！如果我输了，我和阿温一起加入回家社。就是——把你从文艺社抢过来的意思。」'},
{type:'choice',options:[
  {text:'「好。我来跑。」',affinity:{char:'sy',val:3},next:'sy_true'},
  {text:'「我是文艺社的人，不会退社的。」',affinity:{char:'sy',val:1},next:'sy_good'},
  {text:'沉默',next:'sy_normal'}
]},
{label:'sy_true'},{type:'dialogue',char:'WZ',text:'「好。我来跑。」'},
{type:'narrate',text:'百米赛道。她如箭般冲了出去。跑到终点时她已经站在那里等我——'},
{type:'dialogue',char:'SY',text:'「我不用阿温离开文艺社。我要阿温看我跑完全程。一生。」'},
{type:'bg',id:'gym'},
{type:'narrate',text:'东海大赛。烧盐在女子百米中跑出了第一名。她确定进入全国大赛。'},
{type:'dialogue',char:'SY',text:'「阿温，我拿了第一。然后——你也在看吧？」'},
{type:'dialogue',char:'WZ',text:'「一直都在看。」'},
{type:'dialogue',char:'SY',text:'「那就好。接下来是八百米。人生的八百米。和慢慢追上来的阿温一起。」'},
{type:'dialogue',char:'WZ',text:'「我愿意追上你。」'},
{type:'narrate',text:'她笑了。然后踮起脚尖——在车站月台上，在所有乘客的注视下，烧盐柠檬张开双臂，第一次不是跑开，而是跑了过来。她说「比赛结束。现在是休息时间」。我说「那就休息一辈子吧」。'},
{type:'end',title:'真结局：车站月台的拥抱',subtitle:'烧盐柠檬线 · 好结局'},
{label:'sy_good'},{type:'dialogue',char:'WZ',text:'「我是文艺社的人。不会退社的。」'},
{type:'dialogue',char:'SY',text:'「——我猜到你会这么说。但挑战不变。我要堂堂正正。」'},
{type:'bg',id:'infirmary'},
{type:'narrate',text:'全国大赛后，她坐在保健室病床上，阳光从窗户洒入。她伸出手，抓住了我的手。'},
{type:'dialogue',char:'SY',text:'「我可不是只想让你看我跑步。」'},
{type:'dialogue',char:'WZ',text:'「我知道。」'},
{type:'narrate',text:'窗外传来田径队的口号声。她握着我的手，很暖。'},
{type:'end',title:'好结局：保健室的牵手',subtitle:'烧盐柠檬线 · 好结局'},
{label:'sy_normal'},
{type:'narrate',text:'我什么都没说。她笑了——和平时一模一样的笑容。'},
{type:'dialogue',char:'SY',text:'「没关系。我会一直跑。阿温可以在终点看。」'},
{type:'narrate',text:'她第三次获得全国第三名的那个夏天，我从电视上看到了她的比赛。她的背影依然笔直。依然美丽。也许有些女孩——注定是在别人视线尽头奔跑的存在。'},
{type:'end',title:'普通结局：跑者的背影',subtitle:'烧盐柠檬线 · 普通结局'},

// ===== 小鞠知花线 =====
{label:'route_komari'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'—— 小鞠知花线：「从壳里爬出来的人」——'},
{type:'narrate',text:'天爱星的告白后，我以为最先来找我的是八奈见。结果是小鞠。她没敲门。直接闯进社办，把一叠印刷纸扔在我桌上。'},
{type:'dialogue',char:'XJ',text:'「天爱星的事，我知道。温水是大笨蛋。」'},
{type:'bg',id:'printroom'},
{type:'narrate',text:'几天后。文艺社的印刷室里只有她和我。她够不到高处书架上的纸——每次都要我帮忙。'},
{type:'dialogue',char:'XJ',text:'「……谢谢。」声音很小。但这是她今天第三次不用手机跟我说话。'},
{type:'bg',id:'clubroom'},
{type:'narrate',text:'某天放学后。社办里只有她。她站在窗前，对着空无一人的教室练习——'},
{type:'dialogue',char:'XJ',text:'「大家好——我叫小鞠知花——是文艺社副社长——我们文艺社不废社——」'},
{type:'narrate',text:'我在门口停下了脚步。她没发现我。她正在努力。用自己的方式，从壳里一点点爬出来。'},
{type:'narrate',text:'她发现了我在门口，整个人僵住了。然后她深呼吸——没有用手机。直接开口——'},
{type:'dialogue',char:'XJ',text:'「温水——你看到了对吧。那就不藏了。我有话和你说。练习了很多遍。现在说。我——不再躲在手机后面了。」'},
{type:'choice',options:[
  {text:'「我一直在看你。」',affinity:{char:'xj',val:3},next:'xj_true'},
  {text:'「你说得很好。」',affinity:{char:'xj',val:1},next:'xj_good'},
  {text:'安静等待她说完',next:'xj_normal'}
]},
{label:'xj_true'},{type:'dialogue',char:'WZ',text:'「我一直在看你——从加入文艺社那天开始。」'},
{type:'narrate',text:'她的眼泪夺眶而出。没有声音。只是一直掉。最后放弃——用嘴型说了三个字。『喜欢你』。'},
{type:'dialogue',char:'WZ',text:'「我也是。认真的。」'},
{type:'narrate',text:'那一天，文艺社的社办被夕阳灌满。小鞠知花站在窗前，没有用手机，没有打一个字。从躲在壳里的仓鼠到能用声音传达心意的少女——她花了整整三年的高中时光。在最后这一刻——她不躲了。'},
{type:'end',title:'真结局：社办夕阳下的开口',subtitle:'小鞠知花线 · 好结局'},
{label:'xj_good'},{type:'dialogue',char:'WZ',text:'「你说得很好。」'},
{type:'narrate',text:'她——抽了一下鼻子。然后把手机举起来。屏幕上写着：「那接下来的话，我写给你看」。'},
{type:'narrate',text:'「我 喜 欢 温 水 和 彦」——隔着手机屏幕，我看到她的泪水模糊了显示。'},
{type:'narrate',text:'屏幕上的那七个字是她在心里打了千百遍的句子。我说「我看到了」。她说「那就好」。'},
{type:'end',title:'好结局：手机打出的告白',subtitle:'小鞠知花线 · 好结局'},
{label:'xj_normal'},
{type:'narrate',text:'我等着她。一直等着。但她最终没说出后面的话。只是笑了笑——很小很小的弧度。'},
{type:'dialogue',char:'XJ',text:'「……今天就到这里。明天继续练习。」'},
{type:'narrate',text:'文艺社走上正轨。小鞠能独当一面主持会议了。她是副社长。我是社长。我们是最好的搭档。——这样就够了吧。'},
{type:'end',title:'普通结局：最佳搭档',subtitle:'小鞠知花线 · 普通结局'},

// ===== 白玉璃子线 =====
{label:'route_shiratama'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'—— 白玉璃子线：「假面下的真心」——'},
{type:'narrate',text:'天爱星的告白后，文艺社的气氛变得微妙。白玉璃子——这个一年级的学妹——最近总是沉默。'},
{type:'narrate',text:'某天放学后。社办里只有她和我。她坐在窗边，没有化妆。我第一次看到她素颜的样子。'},
{type:'dialogue',char:'BY',text:'「部长。天爱星学姐的告白……你怎么回答的？部长身边有好多女生呢。八奈见学姐、烧盐学姐、小鞠学姐——还有我。」'},
{type:'dialogue',char:'BY',text:'「让我叫璃子。就一次。其实我一直都在演。可爱的学妹、会撩人的心机女生——都是演出来的。因为真实的我很无趣。」'},
{type:'dialogue',char:'WZ',text:'「那你现在呢。现在也是在演吗？」'},
{type:'dialogue',char:'BY',text:'「现在——不知道。可能是我最接近真实的一次。」'},
{type:'choice',options:[
  {text:'「现在的你，比任何时候都好。」',affinity:{char:'by',val:3},next:'by_true'},
  {text:'「你不需要演。」',affinity:{char:'by',val:1},next:'by_good'},
  {text:'「让我看看真实的你。」',next:'by_normal'}
]},
{label:'by_true'},{type:'dialogue',char:'WZ',text:'「现在的你——不化妆、不笑、不演戏——比任何时候都好。」'},
{type:'narrate',text:'她愣住了。然后——眼泪滑了下来。没有声音。'},
{type:'dialogue',char:'BY',text:'「部长你这样——让我的所有招式都失效了。我不再演了。这就是真实的我——一个不完美、不可爱的普通学妹。这样的我——部长愿意接纳吗？」'},
{type:'narrate',text:'我没说话——牵了她的手。那天下午，我们分享了一杯咖啡——她第一次不加糖。因为——「真正的白玉璃子，喜欢苦的」。'},
{type:'end',title:'真结局：咖啡厅里的真实',subtitle:'白玉璃子线 · 好结局'},
{label:'by_good'},{type:'dialogue',char:'WZ',text:'「你不需要演。做你自己就好。」'},
{type:'dialogue',char:'BY',text:'「部长总是说这种话呢。但我还是很高兴。因为你是第一个看穿的人。」'},
{type:'narrate',text:'合宿最后一天。天台。星空的夜晚。她没有化妆。她说「我不再找替身了。我喜欢部长。不是因为谁的味道。」'},
{type:'end',title:'好结局：素颜的天台告白',subtitle:'白玉璃子线 · 好结局'},
{label:'by_normal'},
{type:'dialogue',char:'WZ',text:'「让我看看真实的你。不用着急。」'},
{type:'narrate',text:'她安静地看着我。然后笑了——和平常一样的、完美的微笑。她始终没有摘下面具。但她在文艺社找到了第二个家。'},
{type:'end',title:'普通结局：可靠的学妹',subtitle:'白玉璃子线 · 普通结局'},

// ===== 马剃天爱星线 =====
{label:'route_tengoku'},{type:'bg',id:'bridge'},
{type:'narrate',text:'—— 马剃天爱星线：「认真的人，认真的喜欢」——'},
{type:'narrate',text:'向山大池的桥上。夕阳把桥面染成橙色。马剃天爱星站在我面前，说出了她的告白。'},
{type:'dialogue',char:'MAX',text:'「温水同学——不，温水和彦。我喜欢你。从你答应做我的推荐人那天开始。」'},
{type:'dialogue',char:'MAX',text:'「这是我第一次认真喜欢一个人。以前我的世界只有学习和学生会。但你来了。你闯进来——把我一直藏起来的那个自己也打开了。」'},
{type:'narrate',text:'她说完了。在等的答案。'},
{type:'choice',options:[
  {text:'「我也喜欢你。」',affinity:{char:'max',val:3},next:'max_true'},
  {text:'「让我慢慢回答你。」',affinity:{char:'max',val:1},next:'max_good'},
  {text:'「给我一点时间。」',next:'max_normal'}
]},
{label:'max_true'},{type:'dialogue',char:'WZ',text:'「我也喜欢你。不是顺手。是真心。」'},
{type:'narrate',text:'她张着嘴，忘了合上。鼻血就这么流下来——她都没注意到。'},
{type:'dialogue',char:'MAX',text:'「我准备了三十种被拒绝后的回应方案——全用不上了——因为我是认真的人！」'},
{type:'dialogue',char:'MAX',text:'「那——从现在开始。请让我当你真正的女朋友。不是推荐的。是正式的。」'},
{type:'narrate',text:'周末的咖啡厅。天爱星坐在我对面，往咖啡里加了三勺糖。'},
{type:'dialogue',char:'WZ',text:'「你不是不喜欢咖啡吗？」'},
{type:'dialogue',char:'MAX',text:'「你喜欢。所以我想习惯。」认真的人，连喜欢一杯不喜欢的饮料都全力以赴。'},
{type:'end',title:'真结局：百分百的认真',subtitle:'马剃天爱星线 · 好结局'},
{label:'max_good'},{type:'dialogue',char:'WZ',text:'「让我慢慢回答你。但不是拒绝——是我也需要认真想。」'},
{type:'dialogue',char:'MAX',text:'「好。我等。多久都等。因为认真的人——认真等答案也是应该的。」'},
{type:'narrate',text:'毕业前夕。同一座桥。同一个夕阳。我说「可能不会是现在。但有一天，我会回答你」。她说「那就够了」。'},
{type:'end',title:'好结局：我会等你的',subtitle:'马剃天爱星线 · 好结局'},
{label:'max_normal'},{type:'dialogue',char:'WZ',text:'「给我一点时间。我不擅长立刻回答。」'},
{type:'dialogue',char:'MAX',text:'「好。但不管答案是什么——我们是最好的搭档。这一点不会变。」'},
{type:'narrate',text:'我们没有在一起。但她成为了我大学也保持联系的朋友。每年选举季，她都会在信里夹一张手写报告卡——字迹永远一丝不苟。'},
{type:'end',title:'普通结局：最好的搭档',subtitle:'马剃天爱星线 · 普通结局'},

// ===== 隐藏线 =====
{label:'route_shikishi'},{type:'bg',id:'cafe'},
{type:'narrate',text:'—— 隐藏线：志喜屋梦子 ——'},
{type:'narrate',text:'圣诞夜。我在咖啡厅偶遇了志喜屋学姐。她一个人坐在角落。'},
{type:'dialogue',char:'ZMX',text:'「温水君。想和我交往吗？」安静的一句话。没有任何征兆。'},
{type:'dialogue',char:'WZ',text:'「……学姐是认真的吗？」'},
{type:'dialogue',char:'ZMX',text:'「不知道。但问出口之后，心跳变快了。」她把一只手放在胸口上。耳廓是红的。'},
{type:'bg',id:'beach'},
{type:'narrate',text:'平安夜的海边。她突然打电话说「来海边」。'},
{type:'dialogue',char:'ZMX',text:'「温水君——很可爱。我还会回来的。那你会等我吗？」'},
{type:'dialogue',char:'WZ',text:'「会。」'},
{type:'narrate',text:'毕业后。她考上了东京的大学。我去车站送她。她第一次——露出了不是「扮的」笑容。浅浅的。真的。'},
{type:'narrate',text:'她进了检票口。走了三步。然后回头——用手比了一个丧尸的手势。我说「学姐你还是没变」。她说「变了。以前我不会回头」。'},
{type:'end',title:'隐藏结局：车站的丧尸',subtitle:'志喜屋梦子 · 隐藏线'},

{label:'route_kaju'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'—— 隐藏线：温水佳树 ——'},
{type:'narrate',text:'在所有女主角中——最早的其实是佳树。从小一起长大的妹妹。永远站在我三步之外的妹妹。'},
{type:'dialogue',char:'JS',text:'「兄长大人。你知道吗——佳树和兄长大人，其实没有血缘关系。」'},
{type:'narrate',text:'我拿着饮料的手停住了。她从小被温水家收养。所以——'},
{type:'dialogue',char:'JS',text:'「佳树只是想——在毕业前，把这件事说出来。这样以后——佳树就不会后悔。」'},
{type:'narrate',text:'后来。她考上了石蕗高中。开始在同一个校园里生活。早晨一起出门。傍晚一起回家。'},
{type:'dialogue',char:'JS',text:'「兄妹也可以一直一直在一起。对吗？」'},
{type:'dialogue',char:'WZ',text:'「……对。你是我妹妹。以前是。现在是。以后也是。」'},
{type:'narrate',text:'她笑了。比任何女生都温柔的笑容。或许有些感情——不用跨越这条线。'},
{type:'end',title:'隐藏结局：永远的妹妹',subtitle:'温水佳树 · 兄控结局'},

{label:'route_harem'},{type:'bg',id:'clubroom'},
{type:'narrate',text:'—— 隐藏线：女性公敌结局 ——'},
{type:'narrate',text:'天爱星的告白后——事情很快就失控了。'},
{type:'narrate',text:'某天放学后。我被叫到文艺社。八奈见、烧盐、小鞠、白玉、佳树——还有天爱星——全部坐在社办的会议桌旁。'},
{type:'dialogue',char:'YN',text:'「温水君。因为你这种不拒绝不主动的行为——是明明显显的女性公敌。我们商量好了，请你按照时间表和每个人约会。」'},
{type:'dialogue',char:'MAX',text:'「是——是惩罚。」天爱星红着脸推了推眼镜。'},
{type:'narrate',text:'于是，我的高中最后一年变成了这样：星期一和八奈见在逃生梯吃便当。星期二去田径场看烧盐训练。星期三帮小鞠搬印刷纸。星期四和天爱星整文件。星期五听白玉的撩拨。周末和佳树购物。'},
{type:'narrate',text:'「败北女角」们这次赢了。因为她们制定规则，她们说了算。而我——温水公敌和彦——永远不会忘记这群人。'},
{type:'end',title:'隐藏结局：女性公敌',subtitle:'修罗场 · 全员结局'},

// ===== STAFF =====
{label:'staff'},{type:'bg',id:'black'},
{type:'narrate',text:'《败北女角太多了！～青春挽回作战～》—— END ——'},
{type:'narrate',text:'原作：雨森たきび《敗北女角太多了！》'},
{type:'narrate',text:'视觉小说改编：dacmh'},
{type:'narrate',text:'引擎：HTML/CSS/JavaScript'},
{type:'narrate',text:'「我们败北女角，永不认输。」——文艺社全员'},
{type:'narrate',text:'感谢游玩！'},
];

// 加载剧本并启动
VN.loadScript(SCRIPT_DATA);
